# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fHconfig_sum_update_ptr_parallel <- function(Hconfig, NewPrior, Logf0Mat, Logf1Mat, threads_nb = 0L) {
    .Call('_qch_fHconfig_sum_update_ptr_parallel', PACKAGE = 'qch', Hconfig, NewPrior, Logf0Mat, Logf1Mat, threads_nb)
}

prior_update_arma_ptr_parallel <- function(Hconfig, fHconfig_sum, OldPrior, Logf0Mat, Logf1Mat, threads_nb = 0L) {
    .Call('_qch_prior_update_arma_ptr_parallel', PACKAGE = 'qch', Hconfig, fHconfig_sum, OldPrior, Logf0Mat, Logf1Mat, threads_nb)
}

fHconfig_sum_update_gaussian_copula_ptr_parallel <- function(Hconfig, NewPrior, Logf0Mat, Logf1Mat, zeta0, zeta1, R, Rinv, threads_nb = 0L) {
    .Call('_qch_fHconfig_sum_update_gaussian_copula_ptr_parallel', PACKAGE = 'qch', Hconfig, NewPrior, Logf0Mat, Logf1Mat, zeta0, zeta1, R, Rinv, threads_nb)
}

prior_update_gaussian_copula_ptr_parallel <- function(Hconfig, fHconfig_sum, OldPrior, Logf0Mat, Logf1Mat, zeta0, zeta1, R, Rinv, threads_nb = 0L) {
    .Call('_qch_prior_update_gaussian_copula_ptr_parallel', PACKAGE = 'qch', Hconfig, fHconfig_sum, OldPrior, Logf0Mat, Logf1Mat, zeta0, zeta1, R, Rinv, threads_nb)
}

R_MLE_update_gaussian_copula_ptr_parallel <- function(Hconfig, fHconfig_sum, OldPrior, Logf0Mat, Logf1Mat, zeta0, zeta1, OldR, OldRinv, RhoIndex, threads_nb = 0L) {
    .Call('_qch_R_MLE_update_gaussian_copula_ptr_parallel', PACKAGE = 'qch', Hconfig, fHconfig_sum, OldPrior, Logf0Mat, Logf1Mat, zeta0, zeta1, OldR, OldRinv, RhoIndex, threads_nb)
}

